spring.application.name=RoomEaseAuth

#Oauth configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
server.port=${PORT:8080}

logging.level.org.springframework.security=info
logging.level.org.springframework.security.oauth2=info
logging.level.org.springframework.security.oauth2.client=info
logging.level.org.springframework.web.client.RestTemplate=info

#Database configuration
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#Redis configuration
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.url=${REDIS_URL}

spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=60000
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=false
spring.data.redis.username=default

#spring.session.store_type = redis
#spring.session.timeout=600

#JWT Secret
JWT_SECRET=${JWT_SECRET}

#email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Razorpay properties

razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}

#Date Format












